### ISSUE TITLE
org.redisson.client.WriteRedisConnectionException: Channel has been closed

### ISSUE THREAD

**Issue by chenchenfang** [apache/kvrocks#736]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

linux：CentOS Linux release 7.9.2009 (Core)
kvrocks：version:2.0.6

### Minimal reproduce step

After Tomcat is started,i used Redisson 3.17.3  to get kvrocks data

### What did you expect to see?

do not throw exception......

### What did you see instead?

org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: (SUBSCRIBE), promise: java.util.concurrent.CompletableFuture@1cea627f[Not completed], params: [{USER_REDIS231}:topic] to channel: [id: 0x2edf3aa0, L:0.0.0.0/0.0.0.0:35480 ! R:192.168.1.131/192.168.1.131:6666]
CAUSE:null
	at org.redisson.client.handler.CommandsQueuePubSub.channelInactive(CommandsQueuePubSub.java:76)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at org.redisson.client.handler.ConnectionWatchdog.channelInactive(ConnectionWatchdog.java:82)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

and then

org.redisson.client.RedisException: Unexpected exception while processing command
CAUSE:io.netty.channel.StacklessClosedChannelException
	at org.redisson.command.CommandAsyncService.convertException(CommandAsyncService.java:276)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:132)
	at org.redisson.RedissonTopic.addListener(RedissonTopic.java:104)
	at org.redisson.cache.LocalCacheListener.add(LocalCacheListener.java:141)
	at org.redisson.RedissonLocalCachedMap.init(RedissonLocalCachedMap.java:97)
	at org.redisson.RedissonLocalCachedMap.<init>(RedissonLocalCachedMap.java:70)
	at org.redisson.Redisson.getLocalCachedMap(Redisson.java:249)
	at tools.ERedisson.getLocalCachedMap(ERedisson.kt:86)
	at tools.ERedisson.getLocalCachedMap$default(ERedisson.kt:80)
	at toredisson.BeanToRedisson.getObjectObjectRLocalCachedMap(BeanToRedisson.kt:650)
	at toredisson.BeanToRedisson.rediscaffecacheL2$lambda-2$lambda-1(BeanToRedisson.kt:411)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### Anything Else?

when i used Redisson 3.13.6 , everything is OK
so maybe there are certain things that kVRocks does not support

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by git-hulk** [comment]
@chenchenfang Thanks for filling the issue, but I can't tell what goes wrong with current error stack. You can use the `monitor` command to see what commands were called when errors happened.

**Comment by chenchenfang** [comment]
> @chenchenfang Thanks for filling the issue, but I can't tell what goes wrong with current error stack. You can use the `monitor` command to see what commands were called when errors happened.

kvrocks  request volume is too large, so i think use the `monitor` not a good idea

Is there another way?

**Comment by git-hulk** [comment]
> > @chenchenfang Thanks for filling the issue, but I can't tell what goes wrong with current error stack. You can use the `monitor` command to see what commands were called when errors happened.
> 
> kvrocks request volume is too large, so i think use the `monitor` not a good idea
> 
> Is there another way?

Yet another way is capture packets with tools like tcpdump.

**Comment by tisonkun** [comment]
> After Tomcat is started,i used Redisson 3.17.3 to get kvrocks data

This is quite vague. I suppose you start a Kvrocks server or cluster in someway. It would be better if you can provide a sample repo to reproduce the issue.

**Comment by cloudInspire** [comment]
my redis version : 3.12.2
have the save question
