### ISSUE TITLE
cmake version validation is broken

### ISSUE THREAD

**Issue by druban** [apache/kvrocks#774]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Version

unstable, 8ffdfaf2d5caf73977a9855066d7e06ecc93c76f

### Minimal reproduce step

% ./x.py build
Traceback (most recent call last):
  File "./x.py", line 312, in <module>
    args.func(**arg_dict)
  File "./x.py", line 95, in build
    check_version(cmake_version, CMAKE_REQUIRE_VERSION, "CMake")
  File "./x.py", line 80, in check_version
    raise RuntimeError(f"{prog_name} {require_version} or higher is required, got: {current}")
RuntimeError: CMake 3.13.0 or higher is required, got: 3.22.2

..
% 

### What did you expect to see?

cmake 3.22.2 should be accepted

### What did you see instead?

cmake 3.22.2 was rejected

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by druban** [comment]
Sorry for the false alarm. Issue seems to be addressed already.
